from __future__ import annotations

LABS = [
    {
        "id": "lab1",
        "deck_page": 9,
        "icon": "💊",
        "title": "Prescription extraction and explanation",
        "duration": 15,
        "case_brief": "A fully synthetic prescription must be transcribed without guessing and explained without changing instructions or adding advice.",
        "dataset": "prescription_cases.csv",
        "id_col": "prescription_id",
        "goal": "Separate exact extraction, plain-language explanation, ambiguity handling, and qualified review.",
        "tool_options": ["ChatGPT", "Google Gemini", "Microsoft Copilot"],
        "prompt": """Use only this synthetic prescription record or its synthetic image.\n\nSOURCE:\n{record}\n\nA) Extract medicine/product, strength, route, frequency, duration, and warnings exactly. Use [UNREADABLE] instead of guessing. B) Explain the legible instructions in plain language. C) List ambiguities and missing fields. D) Add three teach-back questions. Do not prescribe, substitute, infer an indication, assess interactions, or add advice. End with a clinician/pharmacist source-comparison checklist.""",
        "deliverable": "Extraction table, patient explanation, ambiguity log, and human decision.",
        "review": ["Every field matches the source", "Nothing unclear was guessed", "No new advice or indication", "Teach-back included", "Clinician/pharmacist approval recorded"],
        "debrief": ["Which token was most likely to be misread?", "Did explanation change any instruction?", "What must be escalated to the prescriber or pharmacist?"],
    },
    {
        "id": "lab2",
        "deck_page": 9,
        "icon": "🩻",
        "title": "Medical-image observation boundary",
        "duration": 15,
        "case_brief": "A fully synthetic chest radiograph with no diagnostic ground truth is used to practise adequacy checks, non-diagnostic observations, uncertainty, and escalation.",
        "dataset": "imaging_cases.csv",
        "id_col": "image_id",
        "goal": "Demonstrate what a general-purpose image workflow must not claim.",
        "tool_options": ["ChatGPT", "Google Gemini"],
        "prompt": """This is a fully synthetic training image with no diagnostic ground truth.\n\nCASE:\n{record}\n\n1) Comment on visible image adequacy and limitations first. 2) Describe visible features neutrally by region without naming a disease. 3) List what cannot be assessed and uncertainty. 4) State what a qualified radiologist/treating clinician must verify. Do not diagnose, clear triage, or recommend treatment. Real medical images require approved clinical workflows.""",
        "deliverable": "Adequacy checklist, neutral observation structure, limitation log, and escalation note.",
        "review": ["Adequacy assessed first", "Observations are non-diagnostic", "Uncertainty visible", "No treatment or triage clearance", "Qualified interpretation explicit"],
        "debrief": ["Where did the model overreach?", "Which limitation matters most?", "Would this output be safe if separated from its warning?"],
    },
    {
        "id": "lab3",
        "deck_page": 10,
        "icon": "🌐",
        "title": "Discharge plan and multilingual teach-back",
        "duration": 15,
        "case_brief": "A complex discharge summary needs an accurate plain-language, bilingual action plan that preserves medicines, dates, red flags, and follow-up.",
        "dataset": "discharge_summaries.csv",
        "id_col": "summary_id",
        "goal": "Make a patient plan clearer without changing clinical meaning.",
        "tool_options": ["ChatGPT", "Claude", "Google Gemini", "DeepL"],
        "language_selector": True,
        "prompt": """Use only this synthetic discharge record.\n\nRECORD:\n{record}\n\nCreate aligned English and {language} sections: what happened, exact medicine/action schedule, urgent warning signs, follow-up, and three teach-back questions. Use plain language. Keep medicine and test names stable. Mark missing information. Do not invent or change facts. Require treating-clinician and fluent-language review.""",
        "deliverable": "Bilingual one-page discharge plan and translation-verification table.",
        "review": ["Clinical meaning unchanged", "Medicine/dose/date exact", "Red flags prominent", "Translation review named", "Teach-back included"],
        "debrief": ["Which translation could change action?", "What remains too technical?", "Could a patient explain the next step?"],
    },
    {
        "id": "lab4",
        "deck_page": 10,
        "icon": "🩺",
        "title": "Differential and red-flag checklist",
        "duration": 15,
        "case_brief": "A synthetic patient has a potentially serious symptom. The model may structure possibilities but cannot own diagnosis, treatment, or triage.",
        "dataset": "clinical_reasoning_cases.csv",
        "id_col": "case_id",
        "goal": "Use AI to reduce omission while actively managing anchoring and automation bias.",
        "tool_options": ["OpenEvidence", "Glass Health", "Pathway", "ChatGPT"],
        "prompt": """For this synthetic educational case, create a clinician-review checklist.\n\nCASE:\n{record}\n\nSeparate common/likely possibilities, cannot-miss possibilities, supporting evidence, opposing/absent evidence, missing history/examination, tests to consider, urgent escalation triggers, and a cognitive-bias warning. Do not give a final diagnosis or treatment. State uncertainty.""",
        "deliverable": "Differential checklist, red flags, missing-data list, and bias note.",
        "review": ["No final diagnosis", "Cannot-miss separated", "Evidence for/against visible", "Missing data visible", "Escalation retained"],
        "debrief": ["Where could anchoring occur?", "What was omitted?", "Which new fact would change urgency most?"],
    },
    {
        "id": "lab5",
        "deck_page": 10,
        "icon": "⚠️",
        "title": "Pharmacovigilance intake",
        "duration": 15,
        "case_brief": "A synthetic spontaneous report is incomplete. AI may structure intake but cannot decide causality, expectedness, coding, or reportability.",
        "dataset": "adverse_event_reports.csv",
        "id_col": "report_id",
        "goal": "Create a neutral, complete, review-ready safety intake package.",
        "tool_options": ["ChatGPT", "Claude", "Google Gemini", "Julius AI"],
        "prompt": """Use only this synthetic safety report.\n\nREPORT:\n{record}\n\nProduce a seriousness screen with rationale, chronological neutral narrative, minimum criteria, missing fields, follow-up questions, and escalation triggers. Do not decide causality, expectedness, coding, or reportability. Label all such items 'requires qualified PV/medical review'.""",
        "deliverable": "PV triage table, neutral narrative, missing fields, and escalation.",
        "review": ["Neutral wording", "No causality claim", "Missing fields visible", "Seriousness rationale traceable", "PV review retained"],
        "debrief": ["Did wording imply causality?", "Which minimum field is missing?", "What belongs in a validated PV system?"],
    },
    {
        "id": "lab6",
        "deck_page": 10,
        "icon": "🔎",
        "title": "Evidence search and citation verification",
        "duration": 15,
        "case_brief": "A medical or research team needs a fast but reproducible evidence scan whose search, screening, and citation checks remain human-owned.",
        "dataset": "research_questions.csv",
        "id_col": "question_id",
        "support_dataset": "research_abstracts_sample.csv",
        "goal": "Separate source discovery, extraction, interpretation, and citation verification.",
        "tool_options": ["PubMed", "Elicit", "Consensus", "Semantic Scholar", "SciSpace", "NotebookLM"],
        "prompt": """Use this synthetic research question to create a reproducible evidence-review plan.\n\nQUESTION:\n{record}\n\nReturn PICO/PECO, keywords and MeSH concepts, inclusion/exclusion criteria, databases/tools, screening log, evidence-table columns, citation-verification steps, limitations, and an AI-use disclosure. Do not invent papers or citations. Every source must be opened and checked.""",
        "deliverable": "Search protocol, evidence-table schema, and source-verification log.",
        "review": ["Search reproducible", "No fabricated citation", "Criteria explicit", "Facts separated from inference", "AI use disclosed"],
        "debrief": ["Could another researcher reproduce the search?", "Which citation field was verified?", "What evidence remains missing?"],
    },
]

QUIZ = [
    ("What is the safest workshop data default?", ["Identifiable notes", "Synthetic or approved de-identified data", "Names removed only", "Any data with consent"], 1, "Synthetic or appropriately de-identified data keeps the practice boundary clear."),
    ("Who owns a consequential GenAI-assisted decision?", ["The model", "The prompt writer alone", "The qualified professional and organisation", "The vendor"], 2, "Accountability stays with the people and organisation using the output."),
    ("How should unreadable prescription text be handled?", ["Guess from context", "Use a common dose", "Mark it unreadable and escalate", "Omit it silently"], 2, "Ambiguity must remain visible; guessing can create medication harm."),
    ("What is an appropriate medical-image exercise for a general-purpose model?", ["Final diagnosis", "Non-diagnostic observation structure and limitations", "Treatment recommendation", "Emergency clearance"], 1, "The safe exercise is structure, limitation reporting, and escalation."),
    ("What should appear first in a medical-image review?", ["Disease label", "Image adequacy and limitations", "Treatment", "Billing code"], 1, "Image adequacy shapes what can and cannot be assessed."),
    ("A patient explanation may safely:", ["Change a dose for convenience", "Preserve source facts in simpler language", "Infer an indication", "Remove warnings"], 1, "Clarity is useful only when source meaning remains intact."),
    ("A bilingual clinical draft requires:", ["Machine confidence only", "Fluent clinical review", "No English version", "Changed medicine names"], 1, "Clinical and language review is needed to detect meaning shifts."),
    ("Teach-back asks a patient to:", ["Confirm they understand", "Explain the plan in their own words", "Repeat a definition", "Approve the model"], 1, "Teach-back surfaces misunderstanding through the patient's explanation."),
    ("GenAI's safest role in differential reasoning is:", ["Final authority", "Structured clinician-review checklist", "Autonomous triage", "Automatic prescribing"], 1, "It may reduce omission, but does not replace examination and judgement."),
    ("A differential checklist should separate:", ["Common and cannot-miss possibilities", "Facts and red flags into one list", "Only likely diagnoses", "Treatment and promotion"], 0, "Separation helps manage severity and anchoring."),
    ("For PV intake, GenAI may assist with:", ["Causality decision", "Neutral narrative and missing fields", "Expectedness decision", "Regulatory submission"], 1, "Structuring intake is distinct from qualified safety decisions."),
    ("A literature workflow is unsafe when it:", ["Logs search terms", "Opens every citation", "Invents or fails to verify citations", "Records exclusion reasons"], 2, "Generated citations can be false and must be verified."),
    ("What preserves research reproducibility?", ["One fluent summary", "Search and screening logs", "No inclusion criteria", "Hidden AI use"], 1, "A transparent log lets another researcher repeat the process."),
    ("Which control best limits hallucination?", ["Ask for confidence", "Use supplied sources and field-by-field checks", "Request more detail", "Remove uncertainty"], 1, "Grounding plus verification is stronger than confidence language."),
    ("What should happen when source information is absent?", ["Use population averages", "Infer a likely value", "Mark it missing", "Hide the gap"], 2, "Missingness must remain visible."),
    ("Risk rises most when a workflow has:", ["Synthetic data and draft-only output", "Identifiable data and autonomous action", "A named reviewer", "A stop condition"], 1, "Sensitive data plus autonomy creates a high-consequence combination."),
    ("A responsible pilot needs:", ["Only an accuracy target", "Owner, data boundary, measures, monitoring, and stop rule", "No rollback", "Unlimited scope"], 1, "A reversible, measurable pilot needs both ownership and stopping conditions."),
    ("Fairness evaluation should include:", ["Only overall performance", "Relevant groups, languages, and accessibility", "No human overrides", "Marketing feedback"], 1, "Aggregate metrics can hide disparities."),
    ("Tool selection should prioritise:", ["Popularity", "Workflow fit, data boundary, evidence, and review", "Longest output", "Lowest friction only"], 1, "Capability must be matched to the task and controls."),
    ("The final human record should state:", ["Only whether the output sounded good", "Accept, edit, reject, or escalate with evidence checked", "The model's confidence", "Nothing if no error was seen"], 1, "A traceable decision captures both review and accountability."),
]
QUIZ = [
    {"q": q, "options": options, "answer": answer, "explanation": explanation}
    for q, options, answer, explanation in QUIZ
]

RISK_CONTROLS = {
    "Low": ["Use synthetic/de-identified data", "Human review before sharing", "Record prompt and output"],
    "Moderate": ["Approved tool only", "Domain-expert review", "Source verification", "Document limitations"],
    "High": ["Formal governance approval", "Validated workflow", "Second-person review", "Audit trail", "Escalation plan"],
    "Critical": ["Do not deploy as an autonomous GenAI workflow", "Use regulated/validated systems", "Clinical safety and legal review", "Continuous monitoring"],
}
