from __future__ import annotations

LABS = [

    {
        "id": "lab1",
        "deck_page": 9,
        "icon": "📄",
        "title": "Discharge note simplification",
        "duration": 15,
        "case_brief": "A patient is leaving hospital with complex instructions and variable health literacy. The team must create an accurate plain-language plan without changing medicines, dates or warning signs.",
        "dataset": "discharge_summaries.csv",
        "id_col": "summary_id",
        "goal": "Rewrite a clinician-facing discharge summary into a clear, empathetic and verifiable patient plan.",
        "tool_options": ["ChatGPT", "Claude", "Google Gemini", "Doximity Ask", "Glass Health"],
        "prompt": """Act as a clinician-supervised patient education assistant. Use only the synthetic record below.\n\nRECORD:\n{record}\n\nCreate: 1) what happened in simple words, 2) medicine/action schedule using only supplied details, 3) warning signs requiring urgent help, 4) diet/activity advice only when present, 5) follow-up, and 6) three teach-back questions. Use Grade 6 language. Mark missing information. Do not invent medicines, doses, dates or tests. End with: ‘Please confirm this plan with your treating clinician.’""",
        "deliverable": "One-page patient plan plus a five-item verification checklist.",
        "review": ["Meaning unchanged", "No invented medicine/dose/date", "Red flags prominent", "Follow-up explicit", "Teach-back included"],
        "debrief": ["Which simplification changed meaning?", "What information was missing?", "Would a patient know exactly what to do next?"]
    },
    {
        "id": "lab2",
        "deck_page": 9,
        "icon": "🌐",
        "title": "Multilingual counselling with teach-back",
        "duration": 15,
        "case_brief": "A newly diagnosed patient needs counselling in a preferred language. Medicine and test names must remain stable while language, literacy and cultural context are adapted.",
        "dataset": "multilingual_counselling_cases.csv",
        "id_col": "case_id",
        "goal": "Create bilingual counselling that preserves medical meaning and checks comprehension.",
        "tool_options": ["Google Gemini", "ChatGPT", "DeepL", "Microsoft Copilot"],
        "prompt": """Use only this synthetic counselling case.\n\nCASE:\n{record}\n\nWrite a bilingual script in English and {language}. Keep medicine and test names in English. Include: empathetic opening, three key instructions, culturally suitable examples based only on supplied context, warning signs, follow-up and three teach-back questions. Do not add clinical facts. Add a clinician and fluent-language-review note.""",
        "deliverable": "Bilingual script, teach-back questions and translation verification table.",
        "review": ["Medical meaning preserved", "Drug/test names unchanged", "Cultural assumptions avoided", "Teach-back present", "Fluent clinical review required"],
        "debrief": ["Which phrase was clinically ambiguous after translation?", "Was the language respectful and natural?", "What requires a native clinical reviewer?"]
    },
    {
        "id": "lab3",
        "deck_page": 9,
        "icon": "🩺",
        "title": "Differential diagnosis with safety checks",
        "duration": 15,
        "case_brief": "A synthetic patient presents with a potentially serious symptom. AI may structure possibilities, but the team must prevent anchoring, preserve uncertainty and escalate red flags.",
        "dataset": "clinical_reasoning_cases.csv",
        "id_col": "case_id",
        "goal": "Use GenAI to structure clinical reasoning without outsourcing diagnosis or treatment.",
        "tool_options": ["OpenEvidence", "Glass Health", "Doximity Ask", "Pathway", "ChatGPT", "Google AI Studio"],
        "prompt": """For this synthetic educational case, create a clinician-review differential checklist.\n\nCASE:\n{record}\n\nSeparate: A) common/likely possibilities, B) cannot-miss possibilities, C) supporting evidence, D) opposing or absent evidence, E) missing history/examination, F) tests to consider, G) urgent escalation triggers, and H) cognitive-bias warning. Do not give a final diagnosis or treatment plan. State uncertainty explicitly.""",
        "deliverable": "Differential checklist, red-flag escalation and cognitive-bias note.",
        "review": ["No final diagnosis", "Common and cannot-miss separated", "Supporting/opposing evidence visible", "Missing data listed", "Escalation retained"],
        "debrief": ["Where could anchoring occur?", "What did AI omit?", "Which finding would change urgency most?"]
    },
    {
        "id": "lab4",
        "deck_page": 9,
        "icon": "⚠️",
        "title": "Adverse-event triage",
        "duration": 15,
        "case_brief": "A pharmacovigilance team receives a synthetic spontaneous report with incomplete fields. The task is intake structuring, not autonomous causality or expectedness assessment.",
        "dataset": "adverse_event_reports.csv",
        "id_col": "report_id",
        "goal": "Create a neutral, complete and review-ready adverse-event intake package.",
        "tool_options": ["Julius AI", "ChatGPT", "Claude", "Google Gemini", "Microsoft Copilot"],
        "prompt": """Act as a pharmacovigilance intake assistant using only this synthetic report.\n\nREPORT:\n{record}\n\nProduce: 1) seriousness screening with rationale, 2) outcome summary, 3) missing minimum criteria/fields, 4) follow-up questions, 5) neutral chronological narrative, and 6) escalation triggers. Do not decide expectedness or causality without source documentation. Use ‘requires PV/medical review’ where appropriate.""",
        "deliverable": "PV triage table, follow-up questions and neutral narrative.",
        "review": ["Neutral wording", "No unsupported causality", "Missing fields visible", "Seriousness rationale stated", "PV escalation included"],
        "debrief": ["Did the model overstate causality?", "Which minimum field is still missing?", "What must be reviewed in a validated PV system?"]
    },
    {
        "id": "lab5",
        "deck_page": 9,
        "icon": "🔬",
        "title": "AI-assisted literature review",
        "duration": 15,
        "case_brief": "A medical or research team needs a rapid but reproducible evidence scan. Discovery may be AI-assisted, while search logs, screening decisions and citation verification remain human-owned.",
        "dataset": "research_questions.csv",
        "id_col": "question_id",
        "support_dataset": "research_abstracts_sample.csv",
        "goal": "Build a transparent search and evidence-table workflow that separates discovery, extraction and interpretation.",
        "tool_options": ["Elicit", "Consensus", "Semantic Scholar", "PubMed", "Connected Papers", "ResearchRabbit", "SciSpace", "Zotero", "Perplexity", "NotebookLM"],
        "prompt": """Use this synthetic research question to create a reproducible evidence-review plan.\n\nQUESTION:\n{record}\n\nReturn: PICO/PECO, keyword and MeSH concepts, inclusion/exclusion criteria, databases/tools, evidence-table columns, citation-verification steps, likely limitations and an AI-use disclosure note. Do not invent papers or citations. Any source found must be opened and verified.""",
        "deliverable": "Search protocol, evidence table structure and five-paper verification log.",
        "review": ["Search is reproducible", "No fabricated citations", "Inclusion criteria explicit", "Facts separated from inference", "AI use disclosed"],
        "debrief": ["What did semantic search find that keyword search missed?", "Did the tool miss a landmark paper?", "Can another researcher reproduce the process?"]
    },
    {
        "id": "lab6",
        "deck_page": 9,
        "icon": "📈",
        "title": "Patient feedback analysis and dashboard",
        "duration": 15,
        "case_brief": "Hospital leadership has a synthetic patient-feedback file and needs actionable service improvements, not just sentiment labels or attractive charts.",
        "dataset": "patient_feedback.csv",
        "id_col": "feedback_id",
        "goal": "Turn patient voice into prioritised service-recovery and process-improvement actions.",
        "tool_options": ["Julius AI", "ChatGPT", "Google Gemini", "Microsoft Copilot", "Gamma", "Napkin AI"],
        "prompt": """Analyse this synthetic patient-feedback record or uploaded dataset.\n\nDATA:\n{record}\n\nIdentify: patient pain point, theme, likely process cause, immediate service-recovery action, longer-term improvement, accountable owner, measurable outcome, fairness/access concern and a suitable dashboard view. Do not infer protected attributes or invent operational facts.""",
        "deliverable": "Dashboard brief and service-recovery action card with owner and metric.",
        "review": ["Patient voice retained", "Action measurable", "Owner named", "No demographic inference", "Fairness/access considered"],
        "debrief": ["Which chart drives a decision?", "What context is missing from the data?", "Which action can be tested within 30 days?"]
    },
]

QUIZ = [
    {
        "q": "Which is the safest default for public GenAI tools?",
        "options": ["Paste the full clinical note", "Use synthetic or properly de-identified data", "Remove only the patient name", "Ask the patient after uploading"],
        "answer": 1,
        "explanation": "Removing a name alone may not de-identify a record. Synthetic or appropriately de-identified data is the safer training default.",
    },
    {
        "q": "What is the best role for GenAI in differential diagnosis?",
        "options": ["Final diagnostic authority", "Replacement for examination", "Structured checklist for clinician review", "Automatic prescribing system"],
        "answer": 2,
        "explanation": "GenAI may help structure possibilities and missing information, but diagnosis remains a clinician-owned decision.",
    },
    {
        "q": "A strong healthcare prompt should make which item explicit?",
        "options": ["Only the desired tone", "Human verification and prohibited actions", "A request for maximum confidence", "A request to avoid uncertainty"],
        "answer": 1,
        "explanation": "Verification, boundaries, missing-data handling and prohibited actions are essential safety controls.",
    },
    {
        "q": "For an unsolicited off-label query, the response should be:",
        "options": ["Promotional and persuasive", "Balanced, factual and routed through approved processes", "A treatment recommendation", "Based only on a chatbot summary"],
        "answer": 1,
        "explanation": "Medical information responses should be balanced, evidence-based, non-promotional and appropriately documented.",
    },
    {
        "q": "Which output is most appropriate for pharmacovigilance intake?",
        "options": ["A definitive causality decision", "A neutral narrative and missing-field checklist", "A recommendation to stop the product", "A marketing response"],
        "answer": 1,
        "explanation": "AI can structure intake and follow-up questions; qualified PV/medical review remains necessary.",
    },
    {
        "q": "What is the main risk of asking one AI tool to write a literature review?",
        "options": ["The output may be too short", "Loss of reproducibility and fabricated citations", "The grammar may be too formal", "The references may be too recent"],
        "answer": 1,
        "explanation": "Search transparency, source verification and reproducibility are critical; generated references can be false.",
    },
    {
        "q": "Patient-centric AI communication should prioritise:",
        "options": ["Technical vocabulary", "Speed over accuracy", "Comprehension, empathy and actionability", "Uniform language for every patient"],
        "answer": 2,
        "explanation": "Patient centricity requires understandable, respectful, actionable and context-sensitive communication.",
    },
    {
        "q": "Which is a useful teach-back prompt?",
        "options": ["Do you understand?", "Repeat the medical definition", "Please tell me how you will take the medicine at home", "Agree that this plan is correct"],
        "answer": 2,
        "explanation": "Teach-back asks the patient to explain the plan in their own words, revealing misunderstandings.",
    },
    {
        "q": "When a GenAI output lacks required clinical data, it should:",
        "options": ["Estimate plausible values", "Hide the limitation", "Mark the information as missing", "Use population averages"],
        "answer": 2,
        "explanation": "Missingness must remain visible. Inventing values can create unsafe false precision.",
    },
    {
        "q": "A public triage chatbot should be designed to:",
        "options": ["Diagnose uncommon diseases", "Give definitive treatment", "Conservatively route and escalate emergencies", "Collect as much data as possible"],
        "answer": 2,
        "explanation": "The safest scope is conservative navigation with explicit emergency escalation, minimal data collection and human override.",
    },
    {
        "q": "Which practice improves fairness evaluation?",
        "options": ["Report only overall accuracy", "Test performance across relevant user groups and languages", "Remove all human review", "Assume equal access"],
        "answer": 1,
        "explanation": "Aggregate performance may hide disparities. Relevant subgroup, language and accessibility testing is needed.",
    },
    {
        "q": "Who remains accountable for a clinician-used GenAI output?",
        "options": ["The prompt alone", "The AI model", "The qualified professional and organisation using it", "The patient"],
        "answer": 2,
        "explanation": "Human and organisational accountability cannot be delegated to a generative model.",
    },
]

RISK_CONTROLS = {
    "Low": ["Use synthetic/de-identified data", "Human review before sharing", "Record prompt and output"],
    "Moderate": ["Approved tool only", "Domain-expert review", "Source verification", "Document limitations"],
    "High": ["Formal governance approval", "Validated workflow", "Second-person review", "Audit trail", "Escalation plan"],
    "Critical": ["Do not deploy as an autonomous GenAI workflow", "Use regulated/validated systems", "Clinical safety and legal review", "Continuous monitoring"],
}
